Name:          galois-dwarf
Version:       0.2.2.1
License:       BSD3
License-file:  LICENSE
Category:      Data
Author:        Simon Winwood, Eyal Lotem, Erik Charlebois
Copyright:     Simon Winwood, Eyal Lotem, Erik Charlebois
Maintainer:    Simon Winwood <sjw@galois.com>
Stability:     unstable
Cabal-Version: >= 1.10
Build-Type:    Simple
Synopsis:      Parser for DWARF debug format.
Description:   Parser for DWARF debug format.

source-repository head
  type: git
  location: https://github.com/GaloisInc/dwarf.git

library
    build-depends:   base >= 2 && < 5, transformers >= 0.3,
                     bytestring, containers, binary, template-haskell
    hs-source-dirs:  src
    exposed-modules:
      Data.Dwarf
      Data.Dwarf.Internals
    other-modules:
      Data.Dwarf.AT,
      Data.Dwarf.AT.TH,
      Data.Dwarf.ATE,
      Data.Dwarf.CFA,
      Data.Dwarf.Form,
      Data.Dwarf.Frame,
      Data.Dwarf.LNI,
      Data.Dwarf.OP,
      Data.Dwarf.Reader,
      Data.Dwarf.TAG,
      Data.Dwarf.TAG.TH,
      Data.Dwarf.Types
    ghc-options:     -Wall
    default-language: Haskell2010

executable dwarf-dump
  default-language: Haskell2010
  ghc-options: -Wall -Wcompat
  main-is: DwarfDump.hs
  hs-source-dirs: app
  other-modules:
    PrettyPrint,
    ElfLoader
  build-depends:
    base,
    binary,
    bytestring,
    containers,
    elf-edit,
    filepath >= 1.4,
    galois-dwarf,
    optparse-applicative >= 0.16,
    text >= 1.2

test-suite galois-dwarf-tests
  type: exitcode-stdio-1.0
  default-language: Haskell2010
  ghc-options: -Wall -Wcompat
  main-is: Main.hs
  hs-source-dirs: tests
  other-modules:
    Golden,
    SLEB128Tests
  build-depends:
    base,
    binary,
    bytestring,
    directory >= 1.3,
    filepath >= 1.4,
    galois-dwarf,
    mtl,
    process >= 1.6,
    tasty >= 1.4,
    tasty-golden >= 2.3,
    tasty-hunit >= 0.10
