{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TemplateHaskell #-}
{-# OPTIONS_GHC -fno-warn-missing-pattern-synonym-signatures #-}
-- We currently disable -Wmissing-signatures as a way to avoid warnings on
-- GHC 9.2, which emits -Wmissing-signatures warnings related to pattern
-- synonyms even if -Wmissing-pattern-synonym-signatures is disabled. See
-- https://gitlab.haskell.org/ghc/ghc/-/issues/14794#note_424553. If that
-- issue is resolved in a subsequent minor release of GHC 9.2, we can remove
-- this workaround.
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
module Data.Dwarf.TAG where

import           Data.Binary.Get (Get)
import           Data.Dwarf.Internals
import qualified Data.Dwarf.TAG.TH
import           Data.Word (Word64)
import           Numeric (showHex)

data DW_TAG = DW_TAG Word64
  deriving (Eq, Ord)

-- Pattern synonyms and tagName function generated by Template Haskell
$(Data.Dwarf.TAG.TH.makeTagDefs)

instance Show DW_TAG where
  showsPrec p tag@(DW_TAG a) =
    case tagName tag of
      Just r -> showString r
      Nothing -> showParen (p > 10) $ showString "DW_TAG " . showHex a

getDW_TAG :: Get DW_TAG
getDW_TAG = DW_TAG <$> getULEB128
