name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [linux-8.8.4]
        include:
        - name: linux-8.8.4
          ghc-ver: 8.8.4
      # complete all jobs
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Get GHC
      run: |
        ghcup install ghc ${{ matrix.ghc-ver }}
        ghcup install cabal 3.4.0.0
        ghcup set ghc ${{ matrix.ghc-ver }}
    - name: Cache
      uses: actions/cache@v1
      with:
        path: /home/runner/.cabal/store/ghc-${{ matrix.ghc-ver }}
        # Prefer previous SHA hash if it is still cached
        key: ${{ matrix.name }}-${{ github.sha }}
        # otherwise just use most recent build.
        restore-keys: ${{ matrix.name }}
    - name: Link cabal project files
      run: |
        ln -s cabal.project.dist                                  cabal.project
        ln -s cabal.project.werror                                cabal.project.local
        ln -s cabal.project.dist.freeze.ghc-${{ matrix.ghc-ver }} cabal.project.freeze
    - name: Cabal update
      run: cabal update
    - name: Cabal build
      run: cabal build
    - name: Cabal test
      run: cabal test
