name: CI
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        cabal: ["3.14.2.0"]
        ghc: ["9.6.2", "9.8.2", "9.10.1"]
        os: ["ubuntu-24.04"]
      fail-fast: false
    uses: GaloisInc/.github/.github/workflows/haskell-ci.yml@v1
    with:
      cabal: ${{ matrix.cabal }}
      check: false
      # See Note [Parallelism] in `haskell-ci.yml` for why `--ghc-options='-j'`
      # and `--semaphore`.
      configure-flags: --enable-tests --ghc-options='-Wall -Werror -j' --semaphore
      ghc: ${{ matrix.ghc }}
      os: ${{ matrix.os }}
      submodules: "true"
      pre-hook: |
        ln -s cabal.project.dist                 cabal.project
        ln -s cabal.ghc-${{ matrix.ghc }}.config cabal.project.freeze
