name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-ver: ["9.4.5", "9.6.2", "9.8.2"]
        cabal: ["3.12.1.0"]
      # complete all jobs
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Link cabal project files
      run: |
        ln -s cabal.project.dist                                  cabal.project
        ln -s cabal.project.werror                                cabal.project.local
        ln -s cabal.project.dist.freeze.ghc-${{ matrix.ghc-ver }} cabal.project.freeze
    - uses: haskell-actions/setup@v2
      id: setup-haskell
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal }}
    - name: Cache
      uses: actions/cache@v4
      with:
        path: /home/runner/.cabal/store/ghc-${{ matrix.ghc-ver }}
        # Prefer previous SHA hash if it is still cached
        key: linux-${{ matrix.ghc-ver }}-${{ hashFiles('cabal.project.freeze') }}-${{ github.sha }}
        # otherwise just use most recent build.
        restore-keys: linux-${{ matrix.ghc-ver }}-${{ hashFiles('cabal.project.freeze') }}
    - name: Cabal update
      run: cabal update
    - name: Cabal build
      run: cabal build
    - name: Cabal test
      run: cabal test
