name: CI
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        cabal: ["3.14.2.0"]
        ghc: ["9.6.2", "9.8.2", "9.10.1"]
        os: ["ubuntu-24.04"]
      fail-fast: false
    uses: GaloisInc/.github/.github/workflows/haskell-ci.yml@v1.4
    with:
      cabal: ${{ matrix.cabal }}
      check: false
      # See Note [Parallelism] in the `haskell-ci` action for why `-j`.
      configure-flags: --enable-tests --ghc-options='-Wall -Werror -j'
      ghc: ${{ matrix.ghc }}
      os: ${{ matrix.os }}
      submodules: "true"
      pre-hook: |
        ln -s cabal.project.dist                              cabal.project
        ln -s cabal.project.dist.freeze.ghc-${{ matrix.ghc }} cabal.project.freeze
